### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lastChild' of undefined

### ISSUE THREAD

**Issue by littlepea** [randy3k/remote-atom#14]
[Enter steps to reproduce below:]

1. Packages -> Remote Atom -> Start Server

**Atom Version**: 0.170.0
**System**: Mac OS X 10.10.1
**Thrown From**: [remote-atom](https://github.com/randy3k/remote-atom) package, v1.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'lastChild' of undefined

```
At /Users/slam/.atom/packages/remote-atom/lib/status-message.coffee:19

TypeError: Cannot read property 'lastChild' of undefined
  at new StatusMessage (/Users/slam/.atom/packages/remote-atom/lib/status-message.coffee:19:35)
  at Object.module.exports.display (/Users/slam/.atom/packages/remote-atom/lib/status-message.coffee:37:28)
  at Object.module.exports.startserver (/Users/slam/.atom/packages/remote-atom/lib/remote-atom.coffee:129:21)
  at atom-workspace.<anonymous> (/Users/slam/.atom/packages/remote-atom/lib/remote-atom.coffee:117:68)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -0:00.0 remote-atom:start-server (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "remote-atom": {
    "launch_at_startup": true
  }
}
```

### Installed Packages

```coffee
# User
dash, v1.0.0
remote-atom, v1.1.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by littlepea** [comment]
Same after updating to `1.1.10`

**Comment by randy3k** [comment]
That's weird. It should be fixed in 1.1.10. Anyway, you should update atom to the latest version and install remote-atom 1.2.0.

**Comment by littlepea** [comment]
It's ok after full reinstall, thanks

**Comment by randy3k** [comment]
Great, glad that it works for you now. Enjoy~
