### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by stschiff** [randy3k/remote-atom#21]
This error occurs when running rmate with a new file that doesn't exist yet.

**Atom Version**: 1.0.18
**System**: Mac OS X 10.10.4
**Thrown From**: [remote-atom](https://github.com/randy3k/remote-atom) package, v1.2.7

### Stack Trace

Uncaught TypeError: Bad argument

```
At fs.js:0

TypeError: Bad argument
  at TypeError (native)
  at Object.fs.closeSync (fs.js:518:18)
  at Session.parse_line (/Users/schiffels/.atom/packages/remote-atom/lib/remote-atom.coffee:45:20)
  at Session.parse_chunk (/Users/schiffels/.atom/packages/remote-atom/lib/remote-atom.coffee:39:18)
  at Socket.<anonymous> (/Users/schiffels/.atom/packages/remote-atom/lib/remote-atom.coffee:19:14)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:520:20)

```

### Commands

```
     -0:52.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:52.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:52.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:52 core:paste (atom-text-editor.editor.is-focused)
     -0:51.5.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:50.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:49.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:49 core:delete (atom-text-editor.editor.is-focused)
     -0:48.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:35 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:34.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:34.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:20.6.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:20.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:20.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "ide-haskell",
      "haskell-ghc-mod",
      "autocomplete-haskell"
    ]
  },
  "remote-atom": {
    "keep_alive": true,
    "launch_at_startup": true
  }
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.4
language-haskell, v1.4.8
remote-atom, v1.2.7

# Dev
No dev packages
```

**Comment by randy3k** [comment]
Can you be more specific? I cannot reproduce it.

**Comment by stschiff** [comment]
This was an automatic error report that atom asked me to send. When I now try it there doesn't seem to be a problem. If you cannot use the information in the automatic report above, just close this issue. Thanks! Stephan

**Comment by randy3k** [comment]
Ok!
