### ISSUE TITLE
Failed to load the remote-atom package

### ISSUE THREAD

**Issue by cobaltjacket** [randy3k/remote-atom#25]
[Enter steps to reproduce below:]

1. Install remote-atom
2. Launch atom

Note that this occurs on various OSes.

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [remote-atom](https://github.com/randy3k/remote-atom) package, v1.3.9

### Stack Trace

Failed to load the remote-atom package

```
At Cannot find module 'mkdirp'

Error: Cannot find module 'mkdirp'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/jph/.atom/packages/remote-atom/lib/remote-atom.coffee:6:10)
    at Object.<anonymous> (/Users/jph/.atom/packages/remote-atom/lib/remote-atom.coffee:1:1)
    at Module._compile (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/package.js:721:27)
    at /Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/package-manager.js:443:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/package-manager.js:393:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Self-Installed/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
remote-atom, v1.3.9
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by randy3k** [comment]
How did you install it? Did you install it via the atom package manager?

**Comment by cobaltjacket** [comment]
I would have, but it wasn't in the list, so I installed it manually, I am not surprised that the latter did not works so perhaps the former is the real issue.

**Comment by randy3k** [comment]
I have no problem in searching remote atom. Do you have issues in installing other packages? Or it is an issue only specific to remote atom?

**Comment by randy3k** [comment]
Try [updating package dependencies](http://stackoverflow.com/questions/36810276/installing-package-dependencies-in-atom)
