### ISSUE TITLE
Uncaught TypeError: Cannot read property 'set' of null

### ISSUE THREAD

**Issue by rbu** [randy3k/remote-atom#29]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: "Fedora release
**Thrown From**: [remote-atom](https://github.com/randy3k/remote-atom) package, v1.3.9

### Stack Trace

Uncaught TypeError: Cannot read property 'set' of null

```
At /home/rbu/.atom/packages/remote-atom/lib/remote-atom.coffee:134

TypeError: Cannot read property 'set' of null
    at Session.parse_setting (/home/rbu/.atom/packages/remote-atom/lib/remote-atom.coffee:134:18)
    at Session.parse_line (/home/rbu/.atom/packages/remote-atom/lib/remote-atom.coffee:129:14)
    at Session.parse_chunk (/home/rbu/.atom/packages/remote-atom/lib/remote-atom.coffee:115:18)
    at Socket.<anonymous> (/home/rbu/.atom/packages/remote-atom/lib/remote-atom.coffee:99:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

### Commands

```
  4x -0:21.6.0 core:select-page-down (atom-text-editor.editor.is-focused)
  2x -0:19.5.0 core:select-page-up (atom-text-editor.editor.is-focused)
 19x -0:18.8.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:16.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:15.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:13.9.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:13.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:12.3.0 core:select-page-up (atom-text-editor.editor.is-focused)
 11x -0:11.6.0 core:select-down (atom-text-editor.editor.is-focused)
 13x -0:10.7.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:09.7.0 core:select-page-up (atom-text-editor.editor.is-focused)
 27x -0:09.1.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:07.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.8.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:05.5.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "metrics",
      "language-objective-c",
      "autocomplete",
      "autocomplete-plus-jedi",
      "linter",
      "linter-pylint",
      "linter-python-pep8",
      "linter-tidy"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "remote-atom": {
    "launch_at_startup": true,
    "port": 52699
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-zeal, v0.1.3
auto-detect-indentation, v1.1.0
indentation-indicator, v1.0.0
remote-atom, v1.3.9

# Dev
No dev packages
```

**Comment by randy3k** [comment]
which client of rmate are you using?

**Comment by rbu** [comment]
Ruby rmate:

# rmate --version
rmate version 1.5.5 (2013-03-17)

**Comment by randy3k** [comment]
I cannot reproduce it. Are you able to reproduce the error?

**Comment by rbu** [comment]
I can. I get this error when I call rmate with a non-existing path (that I should have the permission to create). Sometimes I get the backtrace mentioned in #23 and sometimes this one. Sorry for not being more specific about this in the first place.

**Comment by randy3k** [comment]
I have no problem with ruby rmate 1.5.8. Perhaps you should update your version of rmate?

**Comment by rbu** [comment]
I've updated rmate to 1.5.8.. Here's a screen recording of what happens. As I mentioned, often times I get the backtrace of #23 and sometimes the backtrace mentioned here. The file does not exist and Atom is open with another (unrelated) directory.

![screenrecord](https://cloud.githubusercontent.com/assets/65913/16796897/4862ceac-48e5-11e6-9b68-ecdd97795a6e.gif)

**Comment by randy3k** [comment]
It seems to be a Windows specific bug.

**Comment by randy3k** [comment]
Could you try the bash rmate? https://github.com/aurora/rmate

**Comment by randy3k** [comment]
If it doesn't work. Repeat the following.

The left window was my local machine and right window is a remote machine.
![untitled](https://cloud.githubusercontent.com/assets/1690993/16805358/cc2401e6-48dd-11e6-89da-37dbcf853e9b.gif)

**Comment by CharlesSS07** [comment]
[Enter steps to reproduce:]

1. rmate anyimage.png

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [remote-atom](https://github.com/randy3k/remote-atom) package 1.3.12


### Stack Trace

Uncaught TypeError: Cannot read property 'set' of null

```
At /Users/cstrauss/.atom/packages/remote-atom/lib/remote-atom.coffee:137

TypeError: Cannot read property 'set' of null
    at Session.parse_setting (/packages/remote-atom/lib/remote-atom.coffee:137:19)
    at Session.parse_line (/packages/remote-atom/lib/remote-atom.coffee:132:14)
    at Session.parse_chunk (/packages/remote-atom/lib/remote-atom.coffee:118:18)
    at /packages/remote-atom/lib/remote-atom.coffee:102:14)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

### Commands

```
     -9:37.2.0 editor:newline (input.hidden-input)
  3x -9:31.2.0 core:move-down (input.hidden-input)
     -9:30.5.0 autocomplete-plus:confirm (input.hidden-input)
     -9:29.7.0 core:move-right (input.hidden-input)
     -9:28.9.0 core:save (input.hidden-input)
     -7:04.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
remote-atom 1.3.12 
```

I don't know if rmate is not supposed to open images but it seems like it should.
Would be awesome if it could.

Below is an image from atom.

<img width="1440" alt="Screen Shot 2020-05-10 at 5 54 33 PM" src="https://user-images.githubusercontent.com/48863875/81513699-8d10a380-92e7-11ea-9e0c-69a6d0552f30.png">

Also, I tried `nc -k -l 52698` and then reproducing the error with -w and -v. However, there was absolutely no output.
