### ISSUE TITLE
[v1.3.10] refuses to uninstall or update

### ISSUE THREAD

**Issue by aronlmin** [randy3k/remote-atom#42]
as the title says, it wont go away and i dont know what got touched on install for me to do it manually

console says 
```htmlout
Uninstalling package remote-atom failed Error: Uninstalling “remote-atom” failed.
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:585:27
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12) Failed to delete remote-atom: EACCES: permission denied, unlink '/Users/aronlilland/.atom/packages/remote-atom/.npmignore'

(anonymous) @ <embedded>:193951
(anonymous) @ <embedded>:54489
(anonymous) @ <embedded>:54508
exit @ <embedded>:54048
triggerExitCallback @ <embedded>:128060
(anonymous) @ <embedded>:128081
(anonymous) @ <embedded>:127942
emitOne @ events.js:101
emit @ events.js:188
_handle.close @ net.js:501
```

**Comment by randy3k** [comment]
Note that support of remote-atom has been deprecated and it seems that it is not a remote-atom specific issue.
